package dev.boreaslab.boreas.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import dev.boreaslab.boreas.core.AuthorityStore
import dev.boreaslab.boreas.engine.CaMaterial
import java.io.File
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Persists the public certificate and encrypted private keys. The encryption key
 * stays in Android Keystore; reads and writes treat both halves as one authority.
 * A missing key or authentication failure returns no material so the core can
 * generate a new authority. The private key remains exposed in process memory
 * while the tunnel runs.
 */
internal class KeystoreAuthorityStore(context: Context) : AuthorityStore {

    private val directory = File(context.filesDir, DIRECTORY)
    private val certificateFile = File(directory, "root.der")
    private val keysFile = File(directory, "authority.bin")

    override suspend fun load(): CaMaterial? = withContext(Dispatchers.IO) {
        if (!certificateFile.isFile || !keysFile.isFile) return@withContext null

        try {
            val certificate = certificateFile.readBytes()
            val sealed = keysFile.readBytes()
            if (certificate.isEmpty() || sealed.size <= IV_BYTES) return@withContext null

            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(
                    Cipher.DECRYPT_MODE,
                    existingKey() ?: return@withContext null,
                    GCMParameterSpec(TAG_BITS, sealed, 0, IV_BYTES),
                )
            }
            val keys = cipher.doFinal(sealed, IV_BYTES, sealed.size - IV_BYTES)
            CaMaterial(certificate, keys)
        } catch (_: GeneralSecurityException) {
            // The key is gone or the ciphertext no longer authenticates; regenerate.
            null
        } catch (_: java.io.IOException) {
            null
        }
    }

    override suspend fun save(material: CaMaterial): Unit = withContext(Dispatchers.IO) {
        directory.mkdirs()

        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, existingKey() ?: freshKey())
        }
        val sealed = cipher.iv + cipher.doFinal(material.keys)

        // Neighbor-then-rename prevents a half-written authority file.
        write(certificateFile, material.certificate)
        write(keysFile, sealed)
    }

    private fun write(target: File, bytes: ByteArray) {
        val staging = File(target.parentFile, "${target.name}.part")
        staging.writeBytes(bytes)
        if (!staging.renameTo(target)) {
            staging.delete()
            throw java.io.IOException("could not replace ${target.name}")
        }
    }

    private fun keystore(): KeyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }

    private fun existingKey(): SecretKey? = (keystore().getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.secretKey

    private fun freshKey(): SecretKey =
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER).apply {
            init(
                KeyGenParameterSpec.Builder(
                    ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    // Always-on and boot restarts have no user available to authenticate.
                    .setUserAuthenticationRequired(false)
                    .build(),
            )
        }.generateKey()

    private companion object {
        const val DIRECTORY = "authority"
        const val PROVIDER = "AndroidKeyStore"
        const val ALIAS = "boreas.authority.v1"
        const val TRANSFORMATION = "AES/GCM/NoPadding"

        /** GCM nonce length generated by the provider. */
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
