package dev.boreaslab.boreas.engine

import dev.boreaslab.boreas.model.EngineConfig
import dev.boreaslab.boreas.model.PlatformConfig
import dev.boreaslab.boreas.model.RuleProfile
import dev.boreaslab.boreas.model.SessionId
import dev.boreaslab.boreas.model.SessionStatus
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import java.util.concurrent.atomic.AtomicReference
import kotlin.random.Random

/**
 * A host that runs the lifecycle without an engine, so the control surface can be
 * reviewed and tested before A2 links the real one.
 *
 * Every snapshot it produces carries simulated = true, and the surface renders that
 * marker wherever it shows a counter. Nothing here is presented as measured: the
 * numbers are generated by [Random] from a per-session seed and describe no real
 * traffic. Debug builds only, and off until the reader turns it on.
 */
public class SimulatedEngineHost(
    private val clock: () -> Long = System::currentTimeMillis,
) : EngineHost {

    override val isAvailable: Boolean = true

    /**
     * The session this host is currently simulating, if any.
     *
     * Identity and configuration are one cell rather than two fields, so they
     * cannot be read in a torn state: there is no instant at which the id belongs
     * to one start and the configuration to another. Held in an [AtomicReference]
     * because [start] and [status] run on different coroutines.
     */
    private data class Live(val session: SessionId, val config: EngineConfig)

    private val live = AtomicReference<Live?>(null)

    override suspend fun start(engine: EngineConfig, platform: PlatformConfig): EngineStart {
        // A real start negotiates with the OS and the core. Hold the Starting state
        // long enough that its design is exercised rather than skipped past.
        delay(START_DELAY_MS)
        // Identity comes from the clock rather than an instance counter. The service
        // builds a host per start, so a per-instance counter restarted at one every
        // time and stamped every session `sim-1`, which made two consecutive sessions
        // indistinguishable in the transition log and defeated the equality check
        // that stops a stale status update landing on a newer session.
        val started = Live(SessionId("sim-${clock()}"), engine)
        live.set(started)
        return EngineStart.Started(
            session = started.session,
            status = SessionStatus.initial(clock(), engine.upstream, simulated = true),
        )
    }

    override suspend fun stop(session: SessionId, reason: StopReason) {
        delay(STOP_DELAY_MS)
        live.updateAndGet { current -> current?.takeIf { it.session != session } }
    }

    /**
     * Counters for a session this host started.
     *
     * A request for any other session completes empty rather than inventing a
     * stream from a default configuration: the honest answer to "how is a session
     * I never started doing" is nothing at all.
     */
    override fun status(session: SessionId): Flow<SessionStatus> = flow {
        val config = live.get()?.takeIf { it.session == session }?.config ?: return@flow
        val random = Random(session.value.hashCode())
        var status = SessionStatus.initial(clock(), config.upstream, simulated = true)
        emit(status)
        while (true) {
            delay(TICK_MS)
            val denied = when (config.profile) {
                RuleProfile.Off -> 0L
                RuleProfile.Standard -> random.nextInt(0, 6).toLong()
                RuleProfile.Strict -> random.nextInt(2, 14).toLong()
            }
            status = status.copy(
                flowsActive = random.nextInt(1, 24).toLong(),
                flowsAccepted = status.flowsAccepted + random.nextInt(3, 40),
                flowsDenied = status.flowsDenied + denied,
                bytesIn = status.bytesIn + random.nextLong(12_000, 900_000),
                bytesOut = status.bytesOut + random.nextLong(4_000, 220_000),
                socketsProtected = status.socketsProtected + random.nextInt(0, 3),
            )
            emit(status)
        }
    }

    private companion object {
        const val START_DELAY_MS = 900L
        const val STOP_DELAY_MS = 400L
        const val TICK_MS = 1_000L
    }
}
