package dev.boreaslab.boreas.engine

import dev.boreaslab.boreas.model.EngineConfig
import dev.boreaslab.boreas.model.PlatformConfig
import dev.boreaslab.boreas.model.RuleProfile
import dev.boreaslab.boreas.model.SessionId
import dev.boreaslab.boreas.model.SessionStatus
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlin.random.Random

/**
 * A host that runs the lifecycle without an engine, so the control surface can be
 * reviewed and tested before A2 links the real one.
 *
 * Every snapshot it produces carries simulated = true, and the surface renders that
 * marker wherever it shows a counter. Nothing here is presented as measured: the
 * numbers are generated by [Random] from a per-session seed and describe no real
 * traffic. Debug builds only, and off until the reader turns it on.
 */
class SimulatedEngineHost(
    private val clock: () -> Long = System::currentTimeMillis,
) : EngineHost {

    override val isAvailable = true

    private var counter = 0

    /** The configuration the running session was started with. Set once, at start. */
    private var running: EngineConfig = EngineConfig()

    override suspend fun start(engine: EngineConfig, platform: PlatformConfig): EngineStart {
        // A real start negotiates with the OS and the core. Hold the Starting state
        // long enough that its design is exercised rather than skipped past.
        delay(START_DELAY_MS)
        counter += 1
        running = engine
        val session = SessionId("sim-$counter")
        return EngineStart.Started(
            session = session,
            status = SessionStatus.initial(clock(), engine.upstream, simulated = true),
        )
    }

    override suspend fun stop(session: SessionId, reason: StopReason) {
        delay(STOP_DELAY_MS)
    }

    override fun status(session: SessionId): Flow<SessionStatus> = flow {
        val config = running
        val random = Random(session.value.hashCode())
        var status = SessionStatus.initial(clock(), config.upstream, simulated = true)
        emit(status)
        while (true) {
            delay(TICK_MS)
            val denied = when (config.profile) {
                RuleProfile.Off -> 0L
                RuleProfile.Standard -> random.nextInt(0, 6).toLong()
                RuleProfile.Strict -> random.nextInt(2, 14).toLong()
            }
            status = status.copy(
                flowsActive = random.nextInt(1, 24).toLong(),
                flowsAccepted = status.flowsAccepted + random.nextInt(3, 40),
                flowsDenied = status.flowsDenied + denied,
                bytesIn = status.bytesIn + random.nextLong(12_000, 900_000),
                bytesOut = status.bytesOut + random.nextLong(4_000, 220_000),
                socketsProtected = status.socketsProtected + random.nextInt(0, 3),
            )
            emit(status)
        }
    }

    private companion object {
        const val START_DELAY_MS = 900L
        const val STOP_DELAY_MS = 400L
        const val TICK_MS = 1_000L
    }
}
